### ISSUE TITLE
MHz

### ISSUE THREAD

**Issue by RSMpy** [Jasdoge/Attiny85-Bootloader-Tutorial#2]
Using this method, what is the attiny85 clock set as during the bootload? 1 or 8 MHz?

Regards

**Comment by Jasdoge** [comment]
Up to you. 8mhz is faster but draws more power.

**Comment by RSMpy** [comment]
Thank for the reply. What I mean is if I follow exactly as described, what is the clock speed set as, 1 MHz?

And how can I change that to 8 MHz?

**Comment by Jasdoge** [comment]
I think you set the clock speed in tools when you upload your sketch, rather than on bootloader. I haven't used this method of programming them in ages, because it's slow and horribly wasteful compared to programming them directly with an Arduino. And I barely ever use attiny85 anymore is it's it's very outdated compared to the newer series of attiny. Sorry.
